### ISSUE TITLE
user_role Admin의 경우 참여수업조회 불가능

### ISSUE THREAD

**Issue by ssigner** [hunsy9/DaechulNoh#6]
### 이슈 내용
- user_role이 Admin(교수)의 경우, 참여수업조회(GET)이 되지 않습니다. 테스트를 위해 강의를 하나 더 만들고 새로고침을 했으나, 여전히 콘솔창에 반환값은 빈 배열만 표시가 됩니다. 학생의 경우, 참여된 수업이 조회가 됩니다.
<img width="619" alt="스크린샷 2024-06-01 오전 5 25 00" src="https://github.com/hunsy9/DaechulNoh/assets/108757425/9e0a3759-a8f8-449c-81d2-8242cd6ba866">

### 상세 내용
- 교수의 경우
<img width="1421" alt="스크린샷 2024-06-01 오전 5 20 03" src="https://github.com/hunsy9/DaechulNoh/assets/108757425/8b04200a-8792-4217-a439-3e73fb1a3611">

- 학생의 경우(아직 프론트 내용이 미구현이고 사이드바를 보면 정상적으로 조회가 되었습니다.)
<img width="1422" alt="스크린샷 2024-06-01 오전 5 14 59" src="https://github.com/hunsy9/DaechulNoh/assets/108757425/bec5e6c2-26fa-4f40-8a64-5545e9ca1ab7">

- classroom.js
```classroom.js
const[classroomList, setClassroomList] = useState([]);
  
  useEffect(() => {
    getLecture();
  }, []);

  const getLecture = async () => {
    try{
      var requestOptions = {
        credentials: 'include',
        method: 'GET',
        redirect: 'follow'
      };
      
      fetch("http://localhost:5555/api/lecture/getlecture", requestOptions)
        .then(response => {
          if(response.ok){
            return response.json();
          }
        })
        .then(result => {
          console.log(result);
          let newClassroomList = [...classroomList];
          newClassroomList = result;
          setClassroomList(newClassroomList);
        })
        .catch(error => console.log('error', error));
    } catch (e) {
      console.log(e);
    }
  }
```

**Comment by J-1ac** [comment]
교수가 수업 생성 시 자동으로 수업에 참여가 안되어서 발생한 이슈 같은데, 지금 수정해서 풀리퀘 넣었습니다. 머지 되고 나서 교수로 새 수업 생성한 후 조회해보시면 될 것 같습니다. 기존 데이터들은 추후에 디비 작업하겠습니다.

**Comment by ssigner** [comment]
네네 잘되는거 확인했습니다 감사합니다.
